### ISSUE TITLE
Undefined reference to `cabsf' error with GCC and -std=c99 or -std=c11 flags

### ISSUE THREAD

**Issue by mrsarm** [Tuplanolla/cheat#3]
When you compile with **GCC** without the *"std"* flag there is no problems, but if you just add to your build process this flag in the compilation process, an error like this is launched:

    Linking C executable out/test_say_hello
    CMakeFiles/test_say_hello.dir/test/test_say_hello.c.o: In function `cheat_check_float_complex':
    test_say_hello.c:(.text+0x7d95): undefined reference to `cabsf'
    CMakeFiles/test_say_hello.dir/test/test_say_hello.c.o: In function `cheat_check_double_complex':
    test_say_hello.c:(.text+0x7fc9): undefined reference to `cabs'
    CMakeFiles/test_say_hello.dir/test/test_say_hello.c.o: In function `cheat_check_long_double_complex':
    test_say_hello.c:(.text+0x81f0): undefined reference to `cabsl'
    collect2: error: ld returned 1 exit status
    make[2]: *** [out/test_say_hello] Error 1
    make[1]: *** [CMakeFiles/test_say_hello.dir/all] Error 2
    make: *** [all] Error 2

I not expert of the ``make`` tool, and I'm using **CMake** to generate the ``Makefile`` to compile.

You can check this error testing it with my simple project here: https://github.com/mrsarm/helloworld-c

If you clone and compile that project without modifications, the build process will work OK, but if you add the flag changing the line https://github.com/mrsarm/helloworld-c/blob/master/CMakeLists.txt#L4:

    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall")

With this:

    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -std=c11")

And then build following the steps in the *README* file https://github.com/mrsarm/helloworld-c/blob/master/README#L13, you will see the error.

**Comment by Tuplanolla** [comment]
Section 3.4 of CHEAT's manual tells you to link `libm` or define `CHEAT_NO_MATH` when using extensions.

**Comment by mrsarm** [comment]
@Tuplanolla, the documentation is not very clear on this, but you are right. Thanks!

**Comment by mrsarm** [comment]
I'm back using CHEAT (by the way it's awesome!) and again I got struggled with this error until I realized that I reported it three years ago, and the solution is here, in the section 3.4.

Anyway, I'll like again to note that the explanation it's not clear for those like me that don't use C frequently, so, to be clear, one of the solution is to include the `libm` libary, which is not an option if you are not really using it, or, define `CHEAT_NO_MATH` **before** the include of _cheats.h_, like this:

```c
#define CHEAT_NO_MATH

#include "cheat.h"
#include "cheats.h"
```

**Comment by Tuplanolla** [comment]
Thank you for the kind words.
I have noted this and intend to address it by the next release,
but I do not currently have the time for it.
