### ISSUE TITLE
Unexpected syntax error on GCC  4.6.3

### ISSUE THREAD

**Issue by blinry** [Tuplanolla/cheat#4]
I made a change to my CHEAT testsuite which caused my Travis test to fail. It's not obvious to me why. On GCC 5.3.0, it compiles okay.

- [Diff between failing and ("fixed") passing versions](https://github.com/nordlicht/nordlicht/compare/f69acc2...a60ea6c79e41)
- [Failing job](https://travis-ci.org/nordlicht/nordlicht/jobs/104062109)
- [Passing job](https://travis-ci.org/nordlicht/nordlicht/jobs/104066734)

Error:

    /home/travis/build/nordlicht/nordlicht/testsuite.c:93:1: error: macro "CHEAT_TEST" passed 3 arguments, but takes just 2

It seems this problem is about the additional comma in curly brackets, but I'm not sure about the reason or how I could fix this.

**Comment by blinry** [comment]
Well, I fixed it [like this](https://github.com/nordlicht/nordlicht/commit/27c697c7dd35668306d6608e4c2e27fa13e12573) for now.

**Comment by Tuplanolla** [comment]
Section 5.3 of CHEAT's manual tells you to enable `__VA_ARGS__` (with `-std=c99` or other such option) or delay the expansion of commas explicitly (with `CHEAT_COMMAS_1({NORDLICHT_STYLE_HORIZONTAL, NORDLICHT_STYLE_VERTICAL})` or any of the alternatives).

**Comment by blinry** [comment]
That's it, thanks. Should have RTFM. Came to me as a surprise because commas seemed to work in round brackets.

Note: Section 3.2 incorrectly refers to "Section 5.5" for solutions.
